from OdooService.config import Config
from OdooService.odoo.client import OdooClient
from OdooService.odoo.helpdesk_service import HelpdeskService
import logging

logging.basicConfig(level=logging.INFO)

def test_helpdesk():
    print("\n" + "="*60)
    print("🆘 Testing Helpdesk Service")
    print("="*60)
    
    # Authenticate
    client = OdooClient(Config.ODOO_URL, Config.ODOO_DB, Config.ODOO_USERNAME, Config.ODOO_API_KEY)
    uid = client.authenticate()
    print(f"✅ Authenticated as UID {uid}")
    
    # Initialize Service
    service = HelpdeskService(client)
    
    # 1. List Teams
    target_team = "CMR-FISCAL REPRESENTATION"
    print(f"\n🔍 Step 1: Searching for '{target_team}' Team...")
    team_id = service.find_team(target_team)
    if team_id:
        print(f"✅ Found Team ID: {team_id}")
    else:
        print(f"⚠️ Team '{target_team}' not found. Using default/fallback.")

    # 2. Create Ticket
    print("\n🆕 Step 2: Creating a Test Ticket...")
    ticket_id = service.create_ticket(
        name="Automation Test - Fiscal Rep [Please Delete]",
        team_name=target_team,
        description="<p>This is a test ticket generated by the <b>HelpdeskService</b> for the Fiscal Representation team.</p>",
        priority="2", # High
        partner_email="anas.benabbou@dkm-customs.com" # Example
    )
    print(f"✅ Ticket Created! ID: {ticket_id}")

    # 3. Add Note
    print("\n📝 Step 3: Adding internal note...")
    service.add_note(ticket_id, "This is an automated system note.", internal=True)
    print("✅ Note added.")
    
    # 4. Search and verify
    print("\n🔎 Step 4: Verifying ticket...")
    ticket = service.get_ticket(ticket_id)
    print(f"   Name: {ticket.get('name')}")
    print(f"   Stage: {ticket.get('stage_id')}")
    print(f"   Priority: {ticket.get('priority')}")
    
    # 5. Fetch Messages
    print("\n📧 Step 5: Fetching ticket messages...")
    messages = service.get_ticket_messages(ticket_id)
    print(f"✅ Found {len(messages)} messages:")
    for msg in messages:
        author = msg['author_id'][1] if msg['author_id'] else msg['email_from'] or "Unknown"
        m_type = msg['message_type'] 
        snippet = msg['body'][:50].replace('\n', ' ') if msg['body'] else ""
        print(f"   [{msg['date']}] {author} ({m_type}): {snippet}...")

    print("\n✅ Verification complete. Please check Odoo and delete ticket.")


if __name__ == "__main__":
    test_helpdesk()
